import { useCallback } from "react";
import { CalendarDays, MessageSquareQuote, Target, Download } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Progress } from "@/components/ui/progress";
import { Button } from "@/components/ui/button";
import { buildWeeklyTimetable, type SkillBandInsight, type TimetableDay } from "@/lib/ieltsDashboard";
import { type TestAttempt } from "@/lib/ieltsPracticeData";

interface Props {
  attempts: TestAttempt[];
  insights: SkillBandInsight[];
}

function generateTimetableHTML(timetable: TimetableDay[]) {
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>IELTS Weekly Study Timetable</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; padding: 40px; color: #1a1a2e; }
  h1 { font-size: 22px; margin-bottom: 4px; }
  .sub { font-size: 12px; color: #666; margin-bottom: 24px; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #1a1a2e; color: #fff; text-align: left; padding: 10px 14px; font-size: 12px; text-transform: uppercase; letter-spacing: .5px; }
  td { padding: 10px 14px; border-bottom: 1px solid #e5e5e5; font-size: 13px; vertical-align: top; }
  tr:nth-child(even) { background: #f8f9fa; }
  .skill { text-transform: capitalize; font-weight: 600; }
  .reason { font-size: 11px; color: #666; margin-top: 2px; }
  .footer { margin-top: 24px; font-size: 10px; color: #999; text-align: center; }
  @media print { body { padding: 20px; } }
</style></head><body>
<h1>📅 IELTS Weekly Study Timetable</h1>
<p class="sub">Auto-generated based on your recent practice performance • ${new Date().toLocaleDateString()}</p>
<table><thead><tr><th>Day</th><th>Focus</th><th>Session</th><th>Duration</th></tr></thead><tbody>
${timetable.map(d => `<tr><td><strong>${d.day}</strong></td><td class="skill">${d.skill}</td><td>${d.session}<div class="reason">${d.reason}</div></td><td>${d.duration}</td></tr>`).join("")}
</tbody></table>
<p class="footer">Generated by IELTS Prep Hub • For personal study use</p>
</body></html>`;
}

export default function IELTSFeedbackPanels({ attempts, insights }: Props) {
  const timetable = buildWeeklyTimetable(attempts);

  const handleExportPDF = useCallback(() => {
    const html = generateTimetableHTML(timetable);
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const printWindow = window.open(url, "_blank");
    if (printWindow) {
      printWindow.onload = () => {
        setTimeout(() => printWindow.print(), 300);
      };
    }
  }, [timetable]);

  if (insights.length === 0 && timetable.length === 0) return null;

  return (
    <Tabs defaultValue="descriptors" className="space-y-4">
      <TabsList className="grid w-full grid-cols-2">
        <TabsTrigger value="descriptors" className="gap-2">
          <MessageSquareQuote className="h-4 w-4" /> Band breakdown
        </TabsTrigger>
        <TabsTrigger value="timetable" className="gap-2">
          <CalendarDays className="h-4 w-4" /> Weekly timetable
        </TabsTrigger>
      </TabsList>

      <TabsContent value="descriptors" className="mt-0 space-y-4">
        <div className="grid gap-4 md:grid-cols-2">
          {insights.map((item) => (
            <Card key={item.skill} className="border-border bg-card card-elevated">
              <CardHeader className="pb-3">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <CardTitle className="text-lg capitalize">{item.skill}</CardTitle>
                    <p className="text-sm text-muted-foreground">Band {item.band.toFixed(1)} estimate</p>
                  </div>
                  <span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary">
                    {item.raw}/{item.max}
                  </span>
                </div>
              </CardHeader>
              <CardContent className="space-y-3">
                <Progress value={item.ratio * 100} className="h-2" />
                <div className="space-y-1">
                  <p className="text-sm font-semibold">{item.descriptor.title}</p>
                  <p className="text-sm text-muted-foreground">{item.descriptor.why}</p>
                </div>
                <div className="rounded-lg border border-border bg-muted/30 p-3 space-y-2">
                  <div>
                    <p className="text-xs uppercase tracking-wider text-muted-foreground">Why this band</p>
                    <p className="text-sm">{item.descriptor.benchmark}</p>
                  </div>
                  <div>
                    <p className="text-xs uppercase tracking-wider text-muted-foreground">Focus next</p>
                    <p className="text-sm">{item.descriptor.focus}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </TabsContent>

      <TabsContent value="timetable" className="mt-0">
        <Card className="border-border bg-card card-elevated">
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle className="flex items-center gap-2 text-lg">
                <Target className="h-4 w-4 text-primary" /> Auto-generated weekly study timetable
              </CardTitle>
              <Button variant="outline" size="sm" className="gap-2" onClick={handleExportPDF}>
                <Download className="h-3.5 w-3.5" /> Print / PDF
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Day</TableHead>
                  <TableHead>Focus</TableHead>
                  <TableHead>Session</TableHead>
                  <TableHead>Time</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {timetable.map((item) => (
                  <TableRow key={item.day}>
                    <TableCell className="font-medium">{item.day}</TableCell>
                    <TableCell className="capitalize">{item.skill}</TableCell>
                    <TableCell>
                      <div>
                        <p className="font-medium">{item.session}</p>
                        <p className="text-xs text-muted-foreground">{item.reason}</p>
                      </div>
                    </TableCell>
                    <TableCell>{item.duration}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </TabsContent>
    </Tabs>
  );
}